In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\vrish\OneDrive\Desktop\LbCDA\data.csv")

In [2]:
from sklearn.model_selection import train_test_split
X = df.drop("Call Drop Category", axis=1)
y = df["Call Drop Category"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [3]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(class_weight='balanced', random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))
from sklearn.metrics import precision_score
print(precision_score(y_test,y_pred,average='weighted'))
from sklearn.metrics import recall_score
print(recall_score(y_test,y_pred,average='weighted'))
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred,average='weighted'))


              precision    recall  f1-score   support

           0       0.54      0.67      0.60       537
           1       0.87      0.81      0.84      1606
           2       0.99      0.98      0.99      4620

    accuracy                           0.92      6763
   macro avg       0.80      0.82      0.81      6763
weighted avg       0.93      0.92      0.92      6763

[[ 362  167    8]
 [ 269 1308   29]
 [  36   34 4550]]
0.9197101877864853
0.9265501424181255
0.9197101877864853
0.9223647084276203


In [4]:
import joblib
joblib.dump(model, 'call_drop_model.pkl')


['call_drop_model.pkl']

In [11]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=20,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42
    )
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))
from sklearn.metrics import precision_score
print(precision_score(y_test,y_pred,average='weighted'))
from sklearn.metrics import recall_score
print(recall_score(y_test,y_pred,average='weighted'))
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred,average='weighted'))

              precision    recall  f1-score   support

           0       0.61      0.64      0.63       537
           1       0.85      0.86      0.85      1606
           2       0.99      0.98      0.99      4620

    accuracy                           0.93      6763
   macro avg       0.82      0.83      0.82      6763
weighted avg       0.93      0.93      0.93      6763

[[ 345  184    8]
 [ 203 1382   21]
 [  13   68 4539]]
0.9265119030016264
0.928467951585596
0.9265119030016264
0.9274293258820139


In [9]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20],
    'min_samples_leaf': [1, 3, 5]
}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    verbose=2,
    scoring='f1_macro'
    )

In [10]:
grid_search.fit(X_train,y_train)
print("Best Parameters:", grid_search.best_params_)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best Parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'n_estimators': 100}


In [13]:
joblib.dump(model, "rf_best_balanced.pkl")

['rf_best_balanced.pkl']